server:
  port: 14000
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
#  jms:
#    pub-sub-domain: true

queue:
  QUEUE: queue.test
topic:
  TOPIC: topic.test

camel-queue: "activemq:queue:queue.test"
camel-topic: "activemq:topic:topic.test"